/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PressFitRouteImport } from './routes/press-fit'
import { Route as IndexRouteImport } from './routes/index'

const PressFitRoute = PressFitRouteImport.update({
  id: '/press-fit',
  path: '/press-fit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/press-fit': typeof PressFitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/press-fit': typeof PressFitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/press-fit': typeof PressFitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/press-fit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/press-fit'
  id: '__root__' | '/' | '/press-fit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PressFitRoute: typeof PressFitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/press-fit': {
      id: '/press-fit'
      path: '/press-fit'
      fullPath: '/press-fit'
      preLoaderRoute: typeof PressFitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PressFitRoute: PressFitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
