/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as PressFitRouteImport } from './routes/press-fit'
import { Route as FieldNotesRouteImport } from './routes/field-notes'
import { Route as IndexRouteImport } from './routes/index'

const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const PressFitRoute = PressFitRouteImport.update({
  id: '/press-fit',
  path: '/press-fit',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldNotesRoute = FieldNotesRouteImport.update({
  id: '/field-notes',
  path: '/field-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/field-notes': typeof FieldNotesRoute
  '/press-fit': typeof PressFitRoute
  '/shops': typeof ShopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/field-notes': typeof FieldNotesRoute
  '/press-fit': typeof PressFitRoute
  '/shops': typeof ShopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/field-notes': typeof FieldNotesRoute
  '/press-fit': typeof PressFitRoute
  '/shops': typeof ShopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/field-notes' | '/press-fit' | '/shops'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/field-notes' | '/press-fit' | '/shops'
  id: '__root__' | '/' | '/field-notes' | '/press-fit' | '/shops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FieldNotesRoute: typeof FieldNotesRoute
  PressFitRoute: typeof PressFitRoute
  ShopsRoute: typeof ShopsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press-fit': {
      id: '/press-fit'
      path: '/press-fit'
      fullPath: '/press-fit'
      preLoaderRoute: typeof PressFitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-notes': {
      id: '/field-notes'
      path: '/field-notes'
      fullPath: '/field-notes'
      preLoaderRoute: typeof FieldNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FieldNotesRoute: FieldNotesRoute,
  PressFitRoute: PressFitRoute,
  ShopsRoute: ShopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
